### ISSUE TITLE
question: How should I use it?

### ISSUE THREAD

**Issue by snailgis** [fjorgemota/ol-supercluster#1]
How should I use this package?

**Comment by fjorgemota** [comment]
Hey!

Sorry for the lack of documentation, I need to work at it sometime but I'm not having time right now.

The idea around this package is to have something near the API of the `ol/source/Cluster`, whose documentation you can read [here](https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html). The API isn't exact, tho, because we need some data that `ol/source/Cluster` doesn't need, and a few parameters are renamed to follow supercluster pattern.

IIRC, this is the basic list of changes:

- The constructor needs a `view` option passing the same option you pass to the `view` option of the `ol/Map`;
- The option `distance` is removed;
- There's a new option, called  `radius`, that defines the cluster radius in pixels;
- The option `geometryFunction` is removed;
- There's a new option in it's place called `geoJsonFunction`, which given a `ol/Feature` returns a GeoJSON Feature whose geometry is a Point, [like this](https://github.com/fjorgemota/ol-supercluster/blob/659e390f560ec626202642ce4567a1a232ec128f/src/ol.supercluster.ts#L138-L145).

The rest of the options are basically the same.

If you want, you can look at a demo made by @konscia with a comparison between `ol/source/Cluster` and ol-supercluster usage, [available here](https://github.com/konscia/try-openlayers). The differences for the normal app are minimal, as you can see by comparing the code for the [ol/source/Cluster example](https://github.com/konscia/try-openlayers/blob/29d0f6a94651c92d5e902b4f49086265628b39c4/example-cluster/app.js#L20-L25) and for the [ol-supercluster example](https://github.com/konscia/try-openlayers/blob/29d0f6a94651c92d5e902b4f49086265628b39c4/example-supercluster/app.js#L21-L27).

I hope this helps you. Feel free to ask more questions, I'll answer them ASAP. =)

**Comment by fjorgemota** [comment]
Any new questions @snailgis? If not, I think we can close the issue. :)

**Comment by snailgis** [comment]
thank you very much! I git it

**Comment by fjorgemota** [comment]
Ok. I'll close the issue for now. Feel free to ask more questions anytime by reopening the issue.
